Ot152 210 sql queries f
alkemyTech/OT152-Proyecto-1 pull request #11
Opened 2022-02-18 21:44 UTC by tadeo-vardanega-02

Created two SQL queries for: Universidad De Morón and Universidad Nacional De Río Cuarto

link en jira https://alkemy-labs.atlassian.net/browse/OT152-213

2022-02-20 22:35 UTC, julianpalmerio requested changes
La query de la universidad de moron asi como esta no trae ningun dato. La query de rio cuarto esta trayendo la info de dos universidades, se pide de una sola.

Revisa esto para que lo pueda aprobar, saludos!

2022-02-20 22:35 UTC, julianpalmerio commented on sql/query_moron.sql
> +WHERE universidad = 'Universidad De Morón' AND
El nombre no machea por las mayusculas.

2022-02-20 22:35 UTC, julianpalmerio commented on sql/query_moron.sql
> +DATE(fechaiscripccion) BETWEEN '01/9/2020' AND '01/02/2021';
No esta bien casteada o transformada la fecha de inscripcion.

2022-02-21 00:37 UTC, tadeo-vardanega-02 commented on sql/query_moron.sql
> +DATE(fechaiscripccion) BETWEEN '01/9/2020' AND '01/02/2021';
Mando este mensaje para avisar que ya arregle los 2 archivos

2022-02-23 03:21 UTC, julianpalmerio requested changes
En ambas querys te estaria faltando la fecha de nacimiento, para luego calcular la edad, en una futura tarea.

Por otro lado, el codigo se esta subiendo con algunos problemas, aparentemente de encode, fijate que algunos caracteres no se muestran correctamente.

Fijate si lo podes solucionar, o avisame y te ayudo!

2022-02-23 12:51 UTC, tadeo-vardanega-02 commented
El problema julian era que yo estaba trabajando con la consola de postgre y en la consola las tildes se muestran de esa forma rara.
Ahora probe el codigo que actualize en pgadmin y me funciono

2022-02-24 16:11 UTC, julianpalmerio approved these changes

2022-02-24 16:19 UTC, closed without merging