Python operator configuration for queries, move .gitignore to main pr…
alkemyTech/OT152-Proyecto-1 pull request #35
Opened 2022-02-28 05:21 UTC by JoacoAnun

Python Operator configuration for quering two universities (La Pampa and Interamericana)
.gitignore moved to main proyect folder to reach all directories
added .env to gitignore (where credentials are saved)
created template.env in dags folder - template of how is the configuration for the credential file

2022-03-03 23:50 UTC, julianpalmerio requested changes

2022-03-03 23:50 UTC, julianpalmerio commented on dags/dag_universidad_e.py
> +        pampa_query = text(file.read())
Ojo aca estas abriendo un archivo y nunca lo estas cerrando, esto es totalmente desaconsejable y peligroso.
Siempre que se trabaja con archivos se debe utilizar el context manager with open. En este caso

with open(filepath, 'r') as file:
    trabajas con el file aca dentro

el context manager trabaja como un try except que siempre cierra el archivo cuando se termina de ejecutar el codigo en su interior, incluso si algo sale mal y el codigo rompe.

2022-03-03 23:50 UTC, julianpalmerio commented on dags/dag_universidad_e.py
> +        pampa_df.to_csv(f'airflow/dags/OT152-Proyecto-1/csv/universidad_{university}.csv')
me esta fallando porque no encuentra este path, con el path del .sql lo hiciste bien, es por ahi..

2022-03-03 23:50 UTC, julianpalmerio commented on dags/dag_universidad_e.py
> +basepath = path.dirname(__file__)
todo esto estaria mejor dentro de la funcion que lo va a utilizar.

2022-03-04 03:51 UTC, JoacoAnun commented on dags/dag_universidad_e.py
> +        pampa_query = text(file.read())
se corrige con context manager, tambien se cambia nombre de la variable para que sea generica

2022-03-04 03:52 UTC, JoacoAnun commented on dags/dag_universidad_e.py
> +        pampa_df.to_csv(f'airflow/dags/OT152-Proyecto-1/csv/universidad_{university}.csv')
se crea una sentencia if para crear el directorio csv si no existe, tambien se cambia el nombre de la variable para que sea generica

2022-03-04 03:53 UTC, JoacoAnun commented on dags/dag_universidad_e.py
> +basepath = path.dirname(__file__)
basepath se mueve dentro de la funcion query, y se crea funcion start_engine() que devuelve el create_engine de sqlalchemy para la conexion a base de datos

2022-03-07 21:19 UTC, julianpalmerio requested changes

2022-03-07 21:19 UTC, julianpalmerio commented on dags/dag_universidad_e.py
> +        university_df.to_csv(f'airflow/dags/OT152-Proyecto-1/csv/universidad_{university}.csv')
Cuando lo ejecuto me da error, porque dice que este path no existe. Esta resolviendo mal la ruta f'airflow/dags/OT152-Proyecto-1/csv/universidad_{university}.csv'. Fijate que con el sqlpath lo resolviste distinto el path.

2022-03-07 22:34 UTC, julianpalmerio approved these changes

2022-03-07 22:36 UTC, merged