Implementar Python Operator para el grupo de universidades F
alkemyTech/OT152-Proyecto-1 pull request #38
Opened 2022-02-28 23:16 UTC by Joaq33

- añado operadores python para la ejecución y guardado de las consultas sql
- en el operador se usan argumentos para diferenciar los archivos a extraer
- edito el .gitignore para ignorar archivos .csv
[link a task en jira](https://alkemy-labs.atlassian.net/browse/OT152-261?atlOrigin=eyJpIjoiYWRmODI3YzBjOGM5NDc0NDlmZTEzY2NhY2NlNDI1NjEiLCJwIjoiaiJ9)

2022-03-04 00:59 UTC, julianpalmerio requested changes
Lo vi todo muy bien, solo te remarco detalles, y me faltaria que subas el template.env

2022-03-04 00:59 UTC, julianpalmerio commented on dags/dag_universidad_f.py
> +root_folder = path.abspath(path.join(path.dirname(__file__), ".."))
Todo esto lo dejaria dentro de la funcion que va a utilizarlo

2022-03-04 00:59 UTC, julianpalmerio commented on dags/dag_universidad_f.py
> +        response.to_csv(f'{root_folder}/csv/universidad_{university}.csv', index=False)
Si la carpeta csv no esta creada rompe.

2022-03-05 00:12 UTC, Joaq33 commented on dags/dag_universidad_f.py
> +root_folder = path.abspath(path.join(path.dirname(__file__), ".."))
tenía entendido que la conexión a la db debía setearse previo al uso del dag, ahí corrijo

2022-03-07 21:40 UTC, julianpalmerio approved these changes
Ahora esta perfecto. Buen laburo!

2022-03-07 21:48 UTC, merged