Ot152 256 python operator a
alkemyTech/OT152-Proyecto-1 pull request #41
Opened 2022-03-02 20:25 UTC by penalozale

Resumen:
 - Creo archivo template.env y agregamos .env a .gitignore
 - Creamos una carpeta csv
 - Utilizamos un PythonOperator para:
     - Crear una conexión a la base de datos y ejecutar la query del archivo .sql correspondiente a la universidad dada
     - Guardar los datos obtenidos en un archivo csv (utilizando pandas)

2022-03-03 18:35 UTC, penalozale commented
Olvida el link a la tarea en Jira:
[tarea](https://alkemy-labs.atlassian.net/browse/OT152-256?atlOrigin=eyJpIjoiODgyZTk5ZTRlYjdiNDQ0ZjkzNWUwZjA5ZjJhMzZlYzMiLCJwIjoiaiJ9)

2022-03-03 18:35 UTC, penalozale commented
Olvida el link a la tarea en Jira:
[tarea](https://alkemy-labs.atlassian.net/browse/OT152-256?atlOrigin=eyJpIjoiODgyZTk5ZTRlYjdiNDQ0ZjkzNWUwZjA5ZjJhMzZlYzMiLCJwIjoiaiJ9)

2022-03-04 02:45 UTC, julianpalmerio requested changes
En general esta todo muy bien, la idea esta y esta bien encaminado, te deje algunos comentarios para arreglar.

2022-03-04 02:45 UTC, julianpalmerio commented on dags/dag_universidad_a.py
> +engine = create_engine(db_url)
Todo esto podria ir dentro de la funcion que lo va a utilizar

2022-03-04 02:45 UTC, julianpalmerio commented on dags/dag_universidad_a.py
> +    u_villa_maria = os.path.join(project_folder, 'sql', 'query_villa.sql')
No esta funcionando como creo que vos esperas, recorda que airflow no ejecuta el codigo desde el mismo directorio que vos lo haces localmente, intenta con path.dirname(__file__) ;)

2022-03-04 02:45 UTC, julianpalmerio commented on dags/dag_universidad_a.py
> +        query = text(path.read())
Ojo aca estas abriendo un archivo y nunca lo estas cerrando, esto es totalmente desaconsejable y peligroso.
Siempre que se trabaja con archivos se debe utilizar el context manager with open. En este caso

with open(kwargs['file_path'], 'r') as file:
trabajas con el file aca dentro

el context manager trabaja como un try except que siempre cierra el archivo cuando se termina de ejecutar el codigo en su interior, incluso si algo sale mal y el codigo rompe.

2022-03-04 02:45 UTC, julianpalmerio commented on dags/dag_universidad_a.py
> +                                op_kwargs = {'file_path':'u_flores',
Estas pasando 'u_flores' que es un string, no estas pasando la variable u_flores.

2022-03-04 02:45 UTC, julianpalmerio commented on dags/dag_universidad_a.py
> +                                    op_kwargs = {'file_path':'u_villa_maria',
Estas pasando 'u_flores' que es un string, no estas pasando la variable u_villa_maria.

2022-03-06 15:27 UTC, penalozale commented
Julián, ahí modifiqué un poco el código e hice los arreglos que me comentaste.

2022-03-07 22:46 UTC, julianpalmerio requested changes
Te solicito dos cambios en el codigo, por otro lado fijate que los csv se crearian dentro de la carpeta "apache-airflow-aceleracion\airflow\dags\OT152-Proyecto-1\csv" por lo que vi estan todos dejandolo en "apache-airflow-aceleracion\airflow\dags\OT152-Proyecto-1\dags\csv"

2022-03-07 22:46 UTC, julianpalmerio commented on dags/dag_universidad_a.py
> +    return(engine_connect())
Creo que esto no es lo que queres retornar, no?

2022-03-07 22:46 UTC, julianpalmerio commented on dags/dag_universidad_a.py
> +def DB_connection():
Ojo con el estilo de codigo aca, las funciones SIEMPRE se nombran con snake_case.

2022-03-08 00:38 UTC, penalozale commented on dags/dag_universidad_a.py
> +    return(engine_connect())
Eso quería retornar, pero sin en lugar del guíón bajo iría el punto. Ahí si estaría bien, no?

2022-03-08 00:39 UTC, penalozale commented on dags/dag_universidad_a.py
> +def DB_connection():
Si, tenés razón, se me pasó, Ahí lo correjí.

2022-03-08 00:40 UTC, penalozale commented
Respecto a las carpetas, al principio de todo cuando hice el clone nunca me creó la carpeta del proyecto y por eso no la tengo en mis paths. ¿se la podré agregar a mano con mkdir? ¿o tendría que eliminar todo y volver a clonar?

2022-03-09 02:38 UTC, julianpalmerio approved these changes
Ahora si lo veo mucho mejor!

2022-03-09 02:40 UTC, merged