Ot152 224 dag a
alkemyTech/OT152-Proyecto-1 pull request #5
Opened 2022-02-17 23:19 UTC by JoacoAnun

Create a DAG with no operators, to perform ELT in two Universities

LINK:
https://github.com/alkemyTech/OT152-Proyecto-1/tree/OT152-224_DAG_A

LINK Jira:
https://alkemy-labs.atlassian.net/browse/OT152-224?atlOrigin=eyJpIjoiMjdjMGIxMjI4MzIwNGJiY2ExOGQ1MjVkYzgwMWI1ZTAiLCJwIjoiaiJ9

2022-02-18 04:10 UTC, julianpalmerio requested changes
El código esta bien, el DAG funciona sin dar errores, pero te dejo unos comentarios para mejorarlo. Por otro lado veo que hay al menos dos tasks mas para documentar según la tarjeta de jira!

2022-02-18 04:10 UTC, julianpalmerio commented on dags/Universidades_A.py
> +    task_2 = DummyOperator(task_id='ELT_Universidad_Nacional_De_Villa_Maria')
En linea general se usa el mismo task_id como nombre de la variable donde instanciamos el operator, y en minuscula. por ejemplo sql_universidad_flores = DummyOperator(task_id='sql_universidad_flores')

2022-02-18 04:10 UTC, julianpalmerio commented on dags/Universidades_A.py
> +from datetime import datetime, timedelta
Es un detalle, pero esta bueno ordenar los imports según la guía de PEP8, primero los de la librería standard de Python, luego los de librerías de terceros y luego los módulos propios, cada conjunto separado por un espacio.

2022-02-18 18:56 UTC, JoacoAnun commented on dags/Universidades_A.py
> +from datetime import datetime, timedelta
imports acomodados

2022-02-18 18:57 UTC, JoacoAnun commented on dags/Universidades_A.py
> +    task_2 = DummyOperator(task_id='ELT_Universidad_Nacional_De_Villa_Maria')
Se cambiaron los nombres de las variables y agregue las tasks que faltaban

2022-02-20 15:43 UTC, julianpalmerio commented on dags/dag_universidad_a.py
> +    sql_universidad_villa_maria = DummyOperator(task_id='ELT_Universidad_Nacional_De_Villa_Maria')
Ojo que aca que te quedo sin arreglar el task_id, igual lo apruebo asi

2022-02-20 15:43 UTC, merged