PyOperator - pandas_txt - Univ G
alkemyTech/OT152-Proyecto-1 pull request #54
Opened 2022-03-07 15:23 UTC by penalozale

Resumen:
Creamos la siguientes funciones:
 - root_folder : Obtiene el directorio raíz
 - open_csv_files : Lee un archivo .csv con pandas y obtiene un dataframe.
 - process_latinoamericana: normaliza los datos de dicha universidad
 - process_kennedy: normaliza los datos de dicha universidad
Creamos los PythonOperator que ejecuta dichas funciones

[Link Tarea Jira 278 - Pandas y txt](https://alkemy-labs.atlassian.net/browse/OT152-278?atlOrigin=eyJpIjoiYmRmYmZhNWJiM2Y5NDNjMDhmMjY3MmZjZWNjZjQyNjkiLCJwIjoiaiJ9)

[Link Tarea Jira 270 - PythonOperator](https://alkemy-labs.atlassian.net/browse/OT152-270?atlOrigin=eyJpIjoiOTkzYjZkNWM0MzNiNDQ0MDk2ODEzNTg0YzNmZDRkMTUiLCJwIjoiaiJ9)

2022-03-09 03:44 UTC, julianpalmerio requested changes

2022-03-09 03:44 UTC, julianpalmerio commented on dags/dag_universidad_g.py
> +        today = date.today()
esta mal el date.today(), estimo que es datetime.today()

2022-03-09 03:44 UTC, julianpalmerio commented on dags/dag_universidad_g.py
> +        today = date.today()
esta mal el date.today(), estimo que es datetime.today()

2022-03-09 22:02 UTC, penalozale commented on dags/dag_universidad_g.py
> +        today = date.today()
No, es así. Pero me faltó agregar la librería "date" (from datetime). Ahí lo agregué.

2022-03-14 01:11 UTC, julianpalmerio approved these changes

2022-03-14 01:19 UTC, merged