Configurando DAG
alkemyTech/OT152-Proyecto-1 pull request #8
Opened 2022-02-18 20:21 UTC by SolaligueJoel

Se agregaron los dags para cada una de las universidades, con su respectiva documentación

2022-02-20 15:58 UTC, julianpalmerio requested changes
El dag asi como esta da error en airlfow.

![image](https://user-images.githubusercontent.com/8742928/154851664-6fa81404-3a9f-462b-a09a-4911c131774d.png)

Te dejo un par de comentarios!

2022-02-20 15:58 UTC, julianpalmerio commented on dags/config_dag.py
> +    tarea_2= DummyOperator(task_id='Universidad de Palermo')
Los task_id no pueden contener espacios, podes usar _ para separar palabras y escribir siempre en minuscula. Tambien es una buena practica nombrar a la tarea en si de la misma forma que los task_id.

nombre_de_tarea = DummyOperator(task_id='nombre_de_tarea')

2022-02-20 15:58 UTC, julianpalmerio commented on dags/config_dag.py
> +    """
Usemos # para hacer comentarios

2022-02-21 15:57 UTC, SolaligueJoel commented
Changed variables and comments

2022-02-22 00:56 UTC, julianpalmerio requested changes
Te solicito algunos cambios, te dejo los comentarios.
El dag de esta forma no es levantado por airflow.

2022-02-22 00:56 UTC, julianpalmerio commented on dags/dag_universidad_c.py
> +    universidad_de_palermo= DummyOperator(task_id='universidad_de_Palermo')
Ojo con la mayuscula en el task_id. Escribamos siempre con minusculas

2022-02-22 00:56 UTC, julianpalmerio commented on dags/dag_universidad_c.py
> +    universidad_nacional >> universidad_de_palermo
Todo esto deberia ir ideantado dentro del dag.

2022-02-22 00:56 UTC, julianpalmerio commented on dags/dag_universidad_c.py
> +    universidad_nacional >> universidad_de_palermo
Las dos tareas se deberian ejecutar en paralelo

2022-02-22 03:32 UTC, julianpalmerio approved these changes

2022-02-22 03:33 UTC, merged